# Generated by Django 5.1.7 on 2025-03-25 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Relationships', 'Relationships'), ('Trauma & Abuse', 'Trauma & Abuse'), ('Self-Esteem & Self-Worth', 'Self-Esteem & Self-Worth'), ('Spirituality', 'Spirituality'), ('Addiction & Recovery', 'Addiction & Recovery')], max_length=70, unique=True)),
                ('subtopics', models.ManyToManyField(blank=True, related_name='specializations', to='therapy.subtopic')),
                ('topics', models.ManyToManyField(related_name='specializations', to='therapy.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TherapistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='therapist/profile/')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('years_of_experience', models.PositiveIntegerField()),
                ('languages_spoken', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('country', models.CharField(max_length=60)),
                ('specializations', models.ManyToManyField(related_name='therapists', to='therapy.specialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='therapist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='therapy.topic'),
        ),
    ]
