# Generated by Django 5.1.7 on 2025-03-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='languages_spoken',
            field=models.CharField(max_length=60),
        ),
    ]
